;;; glass-theme.el --- dto's semantic color environment

;; Copyright (C) 2012  David O'Toole

;; Author: David O'Toole <dto@gnu.org>

;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to
;; the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
;; Boston, MA 02110-1301, USA.

;;; Commentary:

;; This is my attempt to design a more useful color theme.

;;; Features:

;; - Medium contrast in neutral grays for most text; color and
;;   brightness are used to show structure and/or emphasis, or to
;;   guide the eye (for example, the active mode-line is bright red,
;;   and the cursor is hot pink.)
;; - Some preliminary attempts at semantic color-coding:
;; + heading: indicates structure. yellow italic
;; + notice: things which MAY require your
;;   attention. yellow-on-red. used for incremental search
;;   highlighting, the modeline prompt, show-paren, light-symbol, etc
;; + related: yellow-on-blue
;; + link: yellow-green? you can navigate elsewhere
;; + note: yellow-green italic
;
;; Code:

(deftheme glass "Theme for Emacs Glass.")
(apply 'custom-theme-set-faces 
 '(glass
     (default ((t (:stipple nil :background "gray20" :foreground "gray90" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal))))
     (action-lock-face ((t (:background "gray40" :foreground "yellow"))))
     (blank-space-face ((t (:background "LightGray"))))
     (blank-tab-face ((t (:background "Wheat"))))
     (blue ((t (:foreground "blue"))))
     (bold-italic ((t ( :foreground "beige" ))))
     (border ((t (:background "Grey"))))
     (buffers-tab ((t (:background "gray30" :foreground "LightSkyBlue"))))
     (calendar-today ((t (:underline t))))
     (cell-default-face ((t (:background "white" :foreground "gray30" :box (:line-width 1 :color "gray70")))))
     (cell-mouse-face ((t (:background "deeppink3" :foreground "cyan"))))
     (cell-action-face ((t ( :background "red" :foreground "yellow" ))))
     (cell-axis-face ((t (:background "gray25" :foreground "gray45" :box (:line-width 1 :color "gray35")))))
     (cell-axis-odd-face ((t (:background "gray23" :foreground "gray42" :box (:line-width 1 :color "gray34")))))
     (cell-bang-face ((t ( :background "red" :foreground "cyan" ))))
     (cell-blank-face ((t (:background "gray20" :foreground "white" :box (:line-width 1 :color "gray35")))))
     (cell-blank-odd-face ((t (:background "gray18" :foreground "gray99" :box (:line-width 1 :color "gray34")))))
     (cell-comment-face ((t (:italic t :foreground "white" :slant italic))))
     (cell-compute-cursor-face ((t (:box (:line-width 1 :color "purple")))))
     (cell-cursor-face ((t (:background "yellow" :foreground "black" :box nil))))
     (cell-default-face ((t (:foreground "white"))))
     (cell-elisp-face ((t (:background "OliveDrab" :foreground "white"))))
     (cell-file-face ((t (:foreground "yellowgreen"))))
     (cell-keyword-face ((t (:background "DarkOrchid4" :foreground "white" :box (:line-width 1 :color "gray35")))))
     (cell-lisp-face ((t (:background "white" :foreground "gray50"))))
     (cell-print-face ((t (:background "gray40" :foreground "gray80"))))
     (cell-receive-var-face ((t (:background "mediumblue" :foreground "white"))))
     (cell-selection-face ((t (:background "seagreen" :foreground "cyan"))))
     (cell-send-var-face ((t (:background "mediumblue" :foreground "white"))))
     (cell-subr-face ((t (:background "white" :foreground "gray40"))))
     (cell-text-face ((t (:foreground "yellow"))))
     (cell-wiki-face ((t (:background "darkslateblue" :foreground "white"))))
     (comint-highlight-prompt ((t ( :foreground "white" ))))
     (comint-input-face ((t (:foreground "deepskyblue"))))
     (compilation-column-number ((t (:foreground "gold" :underline t))))
     (compilation-error ((t (:underline "red"))))
     (compilation-info ((t ( :foreground "Green1" ))))
     (compilation-info-face ((t ( :foreground "Green" ))))
     (compilation-line-number ((t (:foreground "gold"))))
     (compilation-warning ((t ( :foreground "Orange" ))))
     (compilation-warning-face ((t ( :foreground "Orange" ))))
     (cperl-array-face ((t ( :foreground "light salmon" ))))
     (cperl-hash-face ((t (:italic t  :foreground "beige" :slant italic ))))
     (cperl-invalid-face ((t (:foreground "white"))))
     (cperl-nonoverridable-face ((t (:foreground "aquamarine"))))
     (cscsd-speedbar-main-section ((t ( :foreground "cyan" ))))
     (cscsd-speedbar-subsection ((t (:foreground "orange" :underline t))))
     (csound-0-opcode-face ((t (:background "red" :foreground "yellow"))))
     (csound-arate-face ((t (:background "chartreuse4" :foreground "yellow"))))
     (csound-comment-face ((t (:background "gray29" :foreground "gray60"))))
     (csound-decls-face ((t (:foreground "yellow" :underline t))))
     (csound-define-face ((t ( :foreground "red" :underline nil ))))
     (csound-equals-face ((t (:background "red" :foreground "yellow"))))
     (csound-flow-face ((t ( :foreground "blue" :underline nil ))))
     (csound-frate-face ((t (:foreground "MediumBlue" :underline nil :weight normal))))
     (csound-funcs-face ((t (:foreground "magenta"))))
     (csound-globs-face ((t (:background "purple" :foreground "pink" :underline "cyan" :weight normal))))
     (csound-i0-face ((t (:background "gray99" :foreground "Violet" :weight normal))))
     (csound-i1-face ((t (:foreground "Sienna" :weight normal))))
     (csound-i2-face ((t (:background "gray91" :foreground "DarkSlateBlue" :weight normal))))
     (csound-i3-face ((t (:background "gray92" :foreground "SteelBlue" :weight normal))))
     (csound-i4-face ((t (:background "gray93" :foreground "Brown" :weight normal))))
     (csound-i5-face ((t (:background "gray94" :foreground "DarkOliveGreen" :weight normal))))
     (csound-i6-face ((t (:background "gray95" :foreground "MediumSeaGreen" :weight normal))))
     (csound-i7-face ((t (:background "gray96" :foreground "Maroon" :weight normal))))
     (csound-i8-face ((t (:background "gray97" :foreground "Plum" :weight normal))))
     (csound-i9-face ((t (:background "gray98" :foreground "OrangeRed" :weight normal))))
     (csound-inout-face ((t (:background "red" :foreground "yellow"))))
     (csound-irate-face ((t (:background "darkolivegreen4" :foreground "yellow"))))
     (csound-krate-face ((t (:background "olivedrab4" :foreground "yellow"))))
     (csound-label-face ((t (:foreground "red" :underline t :weight normal))))
     (csound-opcode-face ((t (:background "midnightblue" :foreground "cyan"))))
     (csound-section-face ((t ( :foreground "Sienna" ))))
     (csound-string-face ((t (:foreground "magenta" :underline nil :weight normal))))
     (csound-table-face ((t (:foreground "yellow"))))
     (csound-tableno-face ((t ( :foreground "red" ))))
     (csound-tempo-face ((t (:foreground "ForestGreen" :weight normal))))
     (csound-wrate-face ((t (:foreground "DodgerBlue" :underline nil :weight normal))))
     (cursor ((t (:background "magenta"))))
     (custom-button ((t (:foreground "gainsboro"))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-changed ((t (:background "blue" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (:foreground "light blue"))))
     (custom-face-tag ((t (:underline t))))
     (custom-group-tag ((t ( :foreground "pale turquoise" ))))
     (custom-group-tag-1 ((t (:foreground "pale turquoise" :underline t))))
     (custom-invalid ((t (:background "red" :foreground "yellow"))))
     (custom-modified ((t (:background "blue" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue"))))
     (custom-state ((t (:foreground "light salmon"))))
     (custom-variable-button ((t ( :underline t ))))
     (custom-variable-tag ((t ( :foreground "turquoise" ))))
     (cvs-filename-face ((t (:foreground "white"))))
     (cvs-handled-face ((t (:foreground "pink"))))
     (cvs-header-face ((t (:foreground "green"))))
     (cvs-marked-face ((t ( :foreground "green3" ))))
     (cvs-msg-face ((t (:foreground "gray85"))))
     (cvs-need-action-face ((t (:foreground "yellow"))))
     (cvs-unknown-face ((t (:foreground "grey"))))
     (cyan ((t (:foreground "cyan"))))
     (diary ((t (:foreground "yellow"))))
     (dired-directory ((t (:foreground "white"))))
     (dired-face-boring ((t (:foreground "Gray65"))))
     (dired-face-executable ((t (:foreground "green"))))
     (dired-face-flagged ((t (:foreground "tomato"))))
     (dired-face-header ((t (:background "grey75" :foreground "gray30"))))
     (dired-face-marked ((t (:italic t :foreground "slate gray" :slant italic))))
     (dired-face-permissions ((t (:foreground "aquamarine"))))
     (dired-face-setuid ((t (:foreground "gray85"))))
     (dired-face-socket ((t (:foreground "gray85"))))
     (dired-face-symlink ((t (:foreground "cyan"))))
     (dired-flagged ((t (:foreground "red"))))
     (dired-header ((t (:italic t :foreground "yellow" :slant italic))))
     (dired-ignored ((t (:foreground "gray50"))))
     (dired-marked ((t (:italic t :background "blue" :foreground "yellow" :slant italic))))
     (dired-symlink ((t (:foreground "IndianRed1"))))
     (display-time-mail-balloon-enhance-face ((t (:background "orange"))))
     (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
     (display-time-mail-face ((t (:background "red" :foreground "yellow"))))
     (display-time-time-balloon-face ((t (:foreground "gray85"))))
     (ebrowse-file-name-face ((t (:italic t :slant italic))))
     (ebrowse-member-attribute-face ((t (:foreground "red"))))
     (ebrowse-member-class-face ((t (:foreground "Gray85"))))
     (ebrowse-progress-face ((t (:background "blue"))))
     (ebrowse-root-class-face ((t ( :foreground "Gray85" ))))
     (ebrowse-tree-mark-face ((t (:foreground "Gray85"))))
     (ecb-bucket-token-face ((t ( ))))
     (ecb-default-general-face ((t (:height 1.0))))
     (ecb-default-highlight-face ((t (:background "magenta" :height 1.0))))
     (ecb-directories-general-face ((t (:height 0.9))))
     (ecb-directory-face ((t (:background "Cyan4"))))
     (ecb-history-face ((t (:background "Cyan4"))))
     (ecb-history-general-face ((t (:height 0.9))))
     (ecb-method-face ((t (:background "Cyan4" :slant normal :weight normal))))
     (ecb-methods-general-face ((t (:slant normal))))
     (ecb-source-face ((t (:background "Cyan4"))))
     (ecb-source-in-directories-buffer-face ((t (:foreground "LightBlue1"))))
     (ecb-sources-face ((t (:foreground "LightBlue1"))))
     (ecb-sources-general-face ((t (:height 0.9))))
     (ecb-token-header-face ((t (:background "Steelblue4"))))
     (ecb-type-token-class-face ((t ( ))))
     (ecb-type-token-enum-face ((t ( ))))
     (ecb-type-token-group-face ((t ( :foreground "dim gray" ))))
     (ecb-type-token-interface-face ((t ( ))))
     (ecb-type-token-struct-face ((t ( ))))
     (ecb-type-token-typedef-face ((t ( ))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Gray30"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Gray30"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Gray30"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Gray30"))))
     (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Gray30"))))
     (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
     (eldoc-highlight-function-argument ((t (:foreground "yellow" :background "blue"))))
     (elscreen-tab-background-face ((t (:background "gray25"))))
     (elscreen-tab-control-face ((t (:background "white"))))
     (elscreen-tab-current-screen-face ((t (:background "blueviolet" :foreground "cyan"))))
     (elscreen-tab-other-screen-face ((t (:background "gray50" :foreground "gray80"))))
     (emacs-wiki-bad-link-face ((t ( :foreground "IndianRed1" ))))
     (emacs-wiki-header-1 ((t (  :height 1.728 :family "helv"))))
     (emacs-wiki-header-2 ((t (  :height 1.44 :family "helv"))))
     (emacs-wiki-header-3 ((t (  :height 1.2 :family "helv"))))
     (emacs-wiki-header-4 ((t (  :family "helv"))))
     (emacs-wiki-header-5 ((t ( ))))
     (emacs-wiki-link-face ((t ( :foreground "khaki" ))))
     (emacs-wiki-verbatim-face ((t (:foreground "gray"))))
     (emms-pbi-current-face ((t ( :foreground "gold2" ))))
     (emms-pbi-mark-marked-face ((t (:italic t :background "gray30" :foreground "slate gray" :slant italic))))
     (emms-pbi-song-face ((t (:foreground "gray60"))))
     (emms-playlist-selected-face ((t ( :foreground "yellow" ))))
     (erc-action-face ((t (:foreground "gray70"))))
     (erc-bold-face ((t ( ))))
     (erc-button ((t ( ))))
     (erc-command-indicator-face ((t ( ))))
     (erc-current-nick-face ((t (:foreground "red" :background "yellow" ))))
;     (erc-current-nick-face ((t (:foreground "cyan"))))
     (erc-dangerous-host-face ((t (:foreground "red"))))
     (erc-default-face ((t (:foreground "gray70"))))
     (erc-direct-msg-face ((t (:foreground "pale green"))))
     (erc-error-face ((t ( :foreground "IndianRed" ))))
     (erc-fool-face ((t (:foreground "Gray85"))))
     (erc-header-line ((t (:background "grey20" :foreground "gray90" :box nil :underline "gray60"))))
     (erc-highlight-face ((t ( :foreground "pale green" ))))
     (erc-input-face ((t (:foreground "gray90"))))
     (erc-inverse-face ((t (:background "steel blue"))))
     (erc-my-nick-face ((t (:foreground "white"))))
     (erc-nick-default-face ((t (:foreground "gold"))))
     (erc-nick-msg-face ((t ( :foreground "green" ))))
     (erc-notice-face ((t (:foreground "gray50"))))
     (erc-pal-face ((t (:foreground "aquamarine"))))
     (erc-prompt-face ((t (:foreground "white"))))
     (erc-timestamp-face ((t (:foreground "gray40"))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "cyan"))))
     (eshell-ls-archive ((t ( :foreground "Orchid" ))))
     (eshell-ls-archive-face ((t ( :foreground "Orchid" ))))
     (eshell-ls-backup ((t (:foreground "LightSalmon"))))
     (eshell-ls-backup-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-clutter ((t ( :foreground "OrangeRed" ))))
     (eshell-ls-clutter-face ((t ( :foreground "OrangeRed" ))))
     (eshell-ls-directory ((t ( :foreground "SkyBlue" ))))
     (eshell-ls-directory-face ((t ( :foreground "SkyBlue" ))))
     (eshell-ls-executable ((t ( :foreground "Green" ))))
     (eshell-ls-executable-face ((t ( :foreground "Green" ))))
     (eshell-ls-missing ((t ( :foreground "Red" ))))
     (eshell-ls-missing-face ((t ( :foreground "Red" ))))
     (eshell-ls-picture-face ((t (:foreground "violet"))))
     (eshell-ls-product ((t (:foreground "LightSalmon"))))
     (eshell-ls-product-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-readonly ((t (:foreground "Pink"))))
     (eshell-ls-readonly-face ((t (:foreground "Pink"))))
     (eshell-ls-special ((t ( :foreground "Magenta" ))))
     (eshell-ls-special-face ((t ( :foreground "Magenta" ))))
     (eshell-ls-symlink ((t ( :foreground "Cyan" ))))
     (eshell-ls-symlink-face ((t ( :foreground "Cyan" ))))
     (eshell-ls-unreadable ((t (:foreground "DarkGrey"))))
     (eshell-ls-unreadable-face ((t (:foreground "DarkGrey"))))
     (eshell-prompt ((t ( :foreground "Pink" ))))
     (eshell-prompt-face ((t ( :foreground "Pink" ))))
     (excerpt ((t (:italic t :slant italic))))
     (ff-paths-non-existant-file-face ((t ( :foreground "gray85" ))))
     (ffap ((t (:background "purple3" :foreground "cyan"))))
     (fg:black ((t (:foreground "black"))))
     (fg:erc-color-face0 ((t (:foreground "white"))))
     (fg:erc-color-face1 ((t (:foreground "beige"))))
     (fg:erc-color-face10 ((t (:foreground "pale goldenrod"))))
     (fg:erc-color-face11 ((t (:foreground "light goldenrod yellow"))))
     (fg:erc-color-face12 ((t (:foreground "light yellow"))))
     (fg:erc-color-face13 ((t (:foreground "yellow"))))
     (fg:erc-color-face14 ((t (:foreground "light goldenrod"))))
     (fg:erc-color-face15 ((t (:foreground "lime green"))))
     (fg:erc-color-face2 ((t (:foreground "lemon chiffon"))))
     (fg:erc-color-face3 ((t (:foreground "light cyan"))))
     (fg:erc-color-face4 ((t (:foreground "powder blue"))))
     (fg:erc-color-face5 ((t (:foreground "sky blue"))))
     (fg:erc-color-face6 ((t (:foreground "dark sea green"))))
     (fg:erc-color-face7 ((t (:foreground "pale green"))))
     (fg:erc-color-face8 ((t (:foreground "medium spring green"))))
     (fg:erc-color-face9 ((t (:foreground "khaki"))))
     (fixed ((t ( ))))
     (fixed-pitch ((t (:family "courier"))))
     (fl-comment-face ((t (:foreground "gray85"))))
     (fl-function-name-face ((t (:foreground "green"))))
     (fl-keyword-face ((t (:foreground "LightGreen"))))
     (fl-string-face ((t (:foreground "light coral"))))
     (fl-type-face ((t (:foreground "cyan"))))
     (flash-message-face-1 ((t ( :background "yellow" :foreground "black" ))))
     (flash-message-face-2 ((t ( :background "red" :foreground "cyan" ))))
     (flyspell-duplicate-face ((t ( :foreground "Gold3" :underline t ))))
     (flyspell-incorrect-face ((t ( :foreground "OrangeRed" :underline t ))))
     (font-latex-sedate-face ((t (:foreground "Gray85"))))
     (font-latex-string-face ((t (:foreground "orange"))))
     (font-latex-warning-face ((t (:foreground "gold"))))
     (font-lock-builtin-face ((t (:foreground "gray70"))))
     (font-lock-comment-delimiter-face ((t (:background "gray18" :foreground "gray25"))))
     (font-lock-comment-face ((t (:background "gray18" :foreground "gray52"))))
     (font-lock-constant-face ((t (:foreground "gold"))))
     (font-lock-doc-face ((t (:foreground "gray60"))))
     (font-lock-doc-string-face ((t (:background "gray20" :foreground "slate gray"))))
     (font-lock-emphasized-face ((t (:foreground "red"))))
     (font-lock-exit-face ((t (:foreground "green"))))
     (font-lock-function-name-face ((t (:foreground "gold"))))
     (font-lock-keyword-face ((t (:foreground "gray70" ))))
     (font-lock-preprocessor-face ((t (:foreground "gray70"))))
     (font-lock-pseudo-keyword-face ((t (:foreground "gray65"))))
     (font-lock-reference-face ((t (:foreground "cyan"))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "gray10"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "yellow"))))
     (font-lock-string-face ((t (:foreground "gray60"))))
     (font-lock-type-face ((t (:foreground "white" :underline "gray50"))))
     (font-lock-variable-name-face ((t (:foreground "gold2"))))
     (font-lock-warning-face ((t (:underline "red"))))
     (fringe ((t (:background "Grey15" :foreground "white"))))
     (gnus-cite-1 ((t (:foreground "light blue"))))
     (gnus-cite-10 ((t (:foreground "medium purple"))))
     (gnus-cite-11 ((t (:foreground "turquoise"))))
     (gnus-cite-2 ((t (:foreground "light cyan"))))
     (gnus-cite-3 ((t (:foreground "light yellow"))))
     (gnus-cite-4 ((t (:foreground "light pink"))))
     (gnus-cite-5 ((t (:foreground "pale green"))))
     (gnus-cite-6 ((t (:foreground "beige"))))
     (gnus-cite-7 ((t (:foreground "orange"))))
     (gnus-cite-8 ((t (:foreground "magenta"))))
     (gnus-cite-9 ((t (:foreground "violet"))))
     (gnus-cite-attribution ((t (:italic t :slant italic))))
     (gnus-cite-attribution-face ((t (:italic t :slant italic))))
     (gnus-cite-face-1 ((t (:foreground "light blue"))))
     (gnus-cite-face-10 ((t (:foreground "medium purple"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:foreground "light cyan"))))
     (gnus-cite-face-3 ((t (:foreground "light yellow"))))
     (gnus-cite-face-4 ((t (:foreground "light pink"))))
     (gnus-cite-face-5 ((t (:foreground "pale green"))))
     (gnus-cite-face-6 ((t (:foreground "beige"))))
     (gnus-cite-face-7 ((t (:foreground "orange"))))
     (gnus-cite-face-8 ((t (:foreground "magenta"))))
     (gnus-cite-face-9 ((t (:foreground "violet"))))
     (gnus-emphasis-bold ((t ( ))))
     (gnus-emphasis-bold-italic ((t (:italic t  :slant italic ))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t ( :underline t ))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t  :underline t :slant italic ))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-group-mail-1 ((t ( :foreground "aquamarine1" ))))
     (gnus-group-mail-1-empty ((t (:foreground "aquamarine1"))))
     (gnus-group-mail-2 ((t ( :foreground "aquamarine2" ))))
     (gnus-group-mail-2-empty ((t (:foreground "aquamarine2"))))
     (gnus-group-mail-3 ((t ( :foreground "aquamarine3" ))))
     (gnus-group-mail-3-empty ((t (:foreground "aquamarine3"))))
     (gnus-group-mail-low ((t ( :foreground "aquamarine4" ))))
     (gnus-group-mail-low-empty ((t (:foreground "aquamarine4"))))
     (gnus-group-news-1 ((t ( :foreground "PaleTurquoise" ))))
     (gnus-group-news-1-empty ((t (:foreground "PaleTurquoise"))))
     (gnus-group-news-2 ((t ( :foreground "turquoise" ))))
     (gnus-group-news-2-empty ((t (:foreground "turquoise"))))
     (gnus-group-news-3 ((t ( ))))
     (gnus-group-news-4 ((t ( ))))
     (gnus-group-news-5 ((t ( ))))
     (gnus-group-news-6 ((t ( ))))
     (gnus-group-news-low ((t ( :foreground "DarkTurquoise" ))))
     (gnus-group-news-low-empty ((t (:foreground "DarkTurquoise"))))
     (gnus-header-content ((t (:italic t :foreground "forest green" :slant italic))))
     (gnus-header-from ((t (:foreground "spring green"))))
     (gnus-header-name ((t (:foreground "SeaGreen"))))
     (gnus-header-newsgroups ((t (:italic t :foreground "yellow" :slant italic))))
     (gnus-header-subject ((t (:foreground "SeaGreen3"))))
     (gnus-picon-face ((t (:background "white" :foreground "black"))))
     (gnus-picon-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-face ((t (:background "white" :foreground "gray30"))))
     (gnus-picons-xbm-face ((t (:background "white" :foreground "gray30"))))
     (gnus-server-agent ((t ( :foreground "PaleTurquoise" ))))
     (gnus-server-agent-face ((t ( :foreground "PaleTurquoise" ))))
     (gnus-server-closed ((t (:italic t :foreground "Light Steel Blue" :slant italic))))
     (gnus-server-closed-face ((t (:italic t :foreground "Light Steel Blue" :slant italic))))
     (gnus-server-denied ((t ( :foreground "Pink" ))))
     (gnus-server-denied-face ((t ( :foreground "Pink" ))))
     (gnus-server-offline ((t ( :foreground "Yellow" ))))
     (gnus-server-offline-face ((t ( :foreground "Yellow" ))))
     (gnus-server-opened ((t ( :foreground "Green1" ))))
     (gnus-server-opened-face ((t ( :foreground "Green1" ))))
     (gnus-signature ((t (:italic t :slant italic))))
     (gnus-splash ((t (:foreground "Brown"))))
     (gnus-summary-cancelled ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient ((t ( :foreground "SkyBlue" ))))
     (gnus-summary-high-read ((t ( :foreground "PaleGreen" ))))
     (gnus-summary-high-ticked ((t ( :foreground "pink" ))))
     (gnus-summary-high-undownloaded ((t ( :foreground "LightGray" ))))
     (gnus-summary-high-unread ((t ( ))))
     (gnus-summary-low-ancient ((t (:italic t :foreground "SkyBlue" :slant italic))))
     (gnus-summary-low-read ((t (:italic t :foreground "PaleGreen" :slant italic))))
     (gnus-summary-low-ticked ((t (:italic t :foreground "pink" :slant italic))))
     (gnus-summary-low-undownloaded ((t (:italic t :foreground "LightGray" :slant italic :weight normal))))
     (gnus-summary-low-unread ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient ((t (:foreground "SkyBlue"))))
     (gnus-summary-normal-read ((t (:foreground "PaleGreen"))))
     (gnus-summary-normal-ticked ((t (:foreground "pink"))))
     (gnus-summary-normal-undownloaded ((t (:foreground "LightGray" :weight normal))))
     (gnus-summary-selected ((t (:underline t))))
     (gnus-x-face ((t (:background "white" :foreground "gray30"))))
     (golisp-anchor-face ((t ( :foreground "yellow" ))))
     (golisp-bullet-face ((t (:foreground "yellow"))))
     (golisp-defxref-name-face ((t ( :foreground "gray60" ))))
     (golisp-xref-face ((t ( :foreground "yellow" ))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "gray30"))))
     (gui-element ((t (:background "Gray80"))))
     (header-line ((t (:background "grey20" :foreground "gray90" :box nil :underline "gray60"))))
     (headline-face ((t ( :background "gray18" :foreground "yellow" ))))
     (help-argument-name ((t (:italic t :foreground "yellow" :slant italic))))
     (help-highlight-face ((t ( :underline t ))))
     (hi-black-b ((t ( ))))
     (hi-black-hb ((t (  :height 1.67 :family "helv"))))
     (hi-blue ((t (:background "light blue"))))
     (hi-blue-b ((t ( :foreground "blue" ))))
     (hi-green ((t (:background "green"))))
     (hi-green-b ((t ( :foreground "green" ))))
     (hi-pink ((t (:background "pink"))))
     (hi-red-b ((t ( :foreground "red" ))))
     (hi-yellow ((t (:background "yellow"))))
     (highlight ((t ( :background "white" :foreground "red" ))))
     (highlight-changes-delete-face ((t (:foreground "gray85" :underline t))))
     (highlight-changes-face ((t (:foreground "gray85"))))
     (highlight-symbol-face ((t (:foreground "gray90" :background "gray35"))))
     (highline-face ((t (:background "gray15"))))
     (highline-vertical-face ((t (:background "lightcyan"))))
     (holiday ((t (:background "chocolate4"))))
     (howm-menu-key-face ((t (:foreground "orange"))))
     (howm-menu-list-face ((t (:foreground "white"))))
     (howm-mode-keyword-face ((t ( :background "dodgerblue2" :foreground "white" ))))
     (howm-mode-ref-face ((t ( :background "ForestGreen" :foreground "yellow" ))))
     (howm-mode-title-face ((t ( :background "DodgerBlue3" :foreground "white" ))))
     (howm-mode-wiki-face ((t (:foreground "cyan"))))
     (howm-reminder-deadline-face ((t (:background "red" :foreground "yellow"))))
     (howm-reminder-defer-face ((t (:background "violetred4" :foreground "magenta"))))
     (howm-reminder-done-face ((t (:background "gray40" :foreground "gray90"))))
     (howm-reminder-normal-face ((t (:background "forestgreen" :foreground "yellow"))))
     (howm-reminder-schedule-face ((t (:background "darkorange2" :foreground "yellow"))))
     (howm-reminder-separator-face ((t (:foreground "black"))))
     (howm-reminder-today-face ((t (:underline "yellow"))))
     (howm-reminder-todo-face ((t (:background "dodgerblue3" :foreground "cyan"))))
     (howm-reminder-tomorrow-face ((t (:italic t :slant italic))))
     (howm-view-hilit-face ((t ( :background "forestgreen" :foreground "yellow" ))))
     (html-helper-bold-face ((t ( ))))
     (html-helper-builtin-face ((t (:foreground "gray85" :underline t))))
     (html-helper-italic-face ((t ( :foreground "yellow" ))))
     (html-helper-underline-face ((t (:underline t))))
     (html-tag-face ((t ( ))))
     (hyper-apropos-heading ((t ( ))))
     (hyper-apropos-major-heading ((t ( ))))
     (hyper-apropos-section-heading ((t ( ))))
     (hyper-apropos-warning ((t ( :foreground "gray85" ))))
     (ibuffer-marked-face ((t (:foreground "gray85"))))
     (idlwave-help-link ((t (:foreground "Blue"))))
     (idlwave-help-link-face ((t (:foreground "Blue"))))
     (idlwave-shell-bp-face ((t (:background "Pink" :foreground "Black"))))
     (info-header-node ((t ( ))))
     (info-header-xref ((t ( :foreground "sky blue" ))))
     (info-menu-header ((t (  :family "helv"))))
     (info-menu-star ((t (:underline t))))
     (info-node ((t ( ))))
     (info-title-1 ((t (  :height 1.728))))
     (info-title-2 ((t (  :height 1.44 ))))
     (info-title-3 ((t (  :height 1.2 ))))
     (info-title-4 ((t (  ))))
     (info-xref ((t ( :foreground "sky blue" ))))
     (info-xref-visited ((t ( :foreground "magenta3" ))))
     (isearch ((t (:background "red" :foreground "yellow"))))
     (isearch-secondary ((t (:background "darkred" :foreground "yellow"))))
     (italic ((t (:italic t :slant italic))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-bug-breakpoint-marker ((t (:background "yellow" :foreground "red"))))
     (jde-java-font-lock-api-face ((t (:foreground "light goldenrod"))))
     (jde-java-font-lock-bold-face ((t ( ))))
     (jde-java-font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "light coral"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "blue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-number-face ((t (:foreground "LightSalmon"))))
     (jde-java-font-lock-operator-face ((t (:foreground "cyan3"))))
     (jde-java-font-lock-package-face ((t (:foreground "steelblue1"))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (lazy-highlight-face ((t ( :foreground "yellow" ))))
     (ld-script-location-counter ((t ( :foreground "gray57" ))))
     (light-symbol-face ((t (:background "blue" :foreground "yellow"))))
     (linemenu-face ((t (:background "gray30"))))
     (linkd-command-face ((t (:background "goldenrod4" :foreground "gold"))))
     (linkd-generic-face ((t (:foreground "aquamarine1"))))
     (linkd-generic-name-face ((t (:background "aquamarine4" :foreground "aquamarine1" :underline "yellow"))))
     (linkd-icon-face ((t (:underline nil))))
     (linkd-star-face ((t (:background "red" :foreground "yellow" :underline nil))))
     (linkd-star-name-face ((t (:background "olivedrab4" :foreground "yellow" :underline "yellow"))))
     (linkd-tag-face ((t (:background "palevioletred3" :foreground "yellow" :underline nil))))
     (linkd-tag-name-face ((t (:background "aquamarine4" :foreground "aquamarine1" :underline "yellow"))))
     (linkd-wiki-face ((t (:foreground "cyan" :underline "yellow"))))
     (list-mode-item-selected ((t (:background "gray68"))))
     (log-view-file-face ((t ( :background "grey70" ))))
     (magenta ((t (:foreground "gray85"))))
     (makefile-space-face ((t (:background "hotpink"))))
     (man-bold ((t ( ))))
     (man-heading ((t ( ))))
     (man-italic ((t (:foreground "yellow"))))
     (man-xref ((t (:underline t))))
     (match ((t (:background "RoyalBlue4"))))
     (message-cited-text ((t (:foreground "orange"))))
     (message-header-cc ((t (:foreground "khaki"))))
     (message-header-contents ((t (:foreground "white"))))
     (message-header-name ((t (:foreground "LightBlue"))))
     (message-header-newsgroups ((t (:italic t  :foreground "MediumAquamarine" :slant italic ))))
     (mesxsage-header-other ((t (:foreground "MediumAquamarine"))))
     (message-header-subject ((t ( :foreground "light cyan" ))))
     (message-header-to ((t ( :foreground "light cyan" ))))
     (message-header-xheader ((t (:foreground "MediumAquamarine"))))
     (message-headers ((t ( :foreground "orange" ))))
     (message-highlighted-header-contents ((t ( ))))
     (message-mml ((t (:foreground "ForestGreen"))))
     (message-separator ((t (:foreground "chocolate"))))
     (message-url ((t ( :foreground "pink" ))))
     (mew-face-body-cite1 ((t (:foreground "LimeGreen"))))
     (mew-face-body-cite2 ((t (:foreground "SkyBlue"))))
     (mew-face-body-cite3 ((t (:foreground "violet"))))
     (mew-face-body-cite4 ((t (:foreground "Gold"))))
     (mew-face-body-cite5 ((t (:foreground "OrangeRed"))))
     (mew-face-body-comment ((t (:foreground "gray50"))))
     (mew-face-body-url ((t ( :foreground "OrangeRed" ))))
     (mew-face-eof-message ((t ( :foreground "LimeGreen" ))))
     (mew-face-eof-part ((t ( :foreground "Gold" ))))
     (mew-face-header-date ((t ( :foreground "LimeGreen" ))))
     (mew-face-header-from ((t ( :foreground "Gold" ))))
     (mew-face-header-important ((t ( :foreground "SkyBlue" ))))
     (mew-face-header-key ((t ( :foreground "LimeGreen" ))))
     (mew-face-header-marginal ((t ( :foreground "gray50" ))))
     (mew-face-header-private ((t ( ))))
     (mew-face-header-subject ((t ( :foreground "OrangeRed" ))))
     (mew-face-header-to ((t ( :foreground "violet" ))))
     (mew-face-header-warning ((t ( :foreground "red" ))))
     (mew-face-header-xmew ((t ( :foreground "chocolate" ))))
     (mew-face-header-xmew-bad ((t ( :foreground "red" ))))
     (mew-face-mark-delete ((t (:foreground "OrangeRed"))))
     (mew-face-mark-escape ((t (:foreground "violet"))))
     (mew-face-mark-refile ((t (:foreground "LimeGreen"))))
     (mew-face-mark-review ((t (:foreground "SkyBlue"))))
     (mew-face-mark-unlink ((t (:foreground "Gold"))))
     (minibuffer-prompt ((t ( :background "red" :foreground "yellow" ))))
     (mmm-default-submode-face ((t (:background "#c0c0c5"))))
     (mmm-face ((t (:background "black" :foreground "green"))))
     (mode-line ((t (:background "red" :foreground "yellow" :box (:line-width -1 :color "red")))))
     (mode-line-buffer-id ((t ( :foreground "white" ))))
     (mode-line-highlight ((t (:background "blueviolet" :foreground "cyan"))))
     (mode-line-inactive ((t (:background "blueviolet" :foreground "cyan"))))
     (modeline-mousable ((t (:background "white" :foreground "purple"))))
     (mouse ((t (:background "Grey"))))
     (my-summary-highlight-face ((t (:background "PaleTurquoise4" :foreground "White"))))
     (my-url-face ((t (:foreground "LightBlue"))))
     (next-error ((t (:background "grey30"))))
     (org-agenda-date ((t (:foreground "white" :background "gray30" :underline "red"))))
     (org-agenda-date-weekend ((t (:foreground "white" :background "gray30" :underline "blue"))))
     (org-code ((t (:foreground "gray70" :background "gray23"))))
     (org-date ((t (:background "forestgreen" :foreground "yellow"))))
     (org-deadline-announce ((t (:foreground "red"))))
     (org-done ((t (:background "gray15" :foreground "gray45"))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-headline-done ((t (:foreground "gray45"))))
     (org-hide ((t (:foreground "gray27"))))
     (org-level-1 ((t ( :foreground "white" :underline "red"))))
     (org-level-2 ((t ( :foreground "yellow" ))))
     (org-level-3 ((t (:foreground "paleturquoise"))))
     (org-level-4 ((t (:foreground "deepskyblue"))))
     (org-level-5 ((t (:foreground "dodgerblue"))))
     (org-level-6 ((t (:foreground "royalblue"))))
     (org-level-7 ((t (:foreground "gray50"))))
     (org-level-8 ((t (:foreground "gray35"))))
     (org-link ((t (:foreground "yellowgreen" :underline "yellow"))))
     (org-property-value ((t (:foreground "greenyellow"))))
     (org-scheduled-previously ((t (:foreground "red"))))
     (org-scheduled-today ((t (:foreground "LightSkyBlue"))))
     (org-special-keyword ((t (:foreground "yellow" :background "gray30"))))
     (org-table ((t (:foreground "yellow" :background "gray15"))))
     (org-meta-line ((t (:foreground "skyblue" :background "gray25"))))
     (org-tag ((t (:background "seagreen" :foreground "cyan"))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:background "red" :foreground "yellow"))))
     (org-warning ((t ( :foreground "Red1" ))))
     (outline-1 ((t (:italic t  :foreground "LightSkyBlue" :slant italic ))))
     (outline-2 ((t (:italic t  :foreground "LightGoldenrod" :slant italic ))))
     (outline-3 ((t ( :foreground "Cyan" ))))
     (outline-4 ((t ( :foreground "LightSteelBlue" ))))
     (outline-5 ((t (:italic t :foreground "medium aquamarine" :slant italic))))
     (outline-6 ((t ( :foreground "Aquamarine" ))))
     (outline-7 ((t ( :foreground "PaleGreen" ))))
     (outline-8 ((t (:italic t :foreground "aquamarine" :slant italic))))
     (paren-blink-off ((t (:foreground "gray80"))))
     (paren-face ((t (:background "gray20"))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "gray30"))))
     (paren-match ((t (:background "darkseagreen2"))))
     (paren-mismatch ((t (:background "RosyBrown" :foreground "gray30"))))
     (paren-mismatch-face ((t ( :background "white" :foreground "red" ))))
     (paren-no-match-face ((t ( :background "white" :foreground "red" ))))
     (planner-cancelled-task-face ((t (:foreground "gray" :strike-through t))))
     (planner-completed-task-face ((t (:foreground "gray" :strike-through t))))
     (planner-delegated-task-face ((t (:italic t :slant italic))))
     (planner-high-priority-task-face ((t (:foreground "red"))))
     (planner-id-face ((t (:foreground "darkgray"))))
     (planner-in-progress-task-face ((t ( ))))
     (planner-low-priority-task-face ((t (:foreground "blue"))))
     (planner-medium-priority-task-face ((t (:foreground "green"))))
     (planner-note-headline-face ((t ( :foreground "dark slate blue" ))))
     (primary-selection ((t (:background "gray40"))))
     (query-replace ((t (:background "slate blue"))))
     (radio-annotation-data-face ((t (:foreground "gray50"))))
     (radio-annotation-delimiter-alt-face ((t (:foreground "gray30" ))))
     (radio-annotation-delimiter-face ((t (:foreground "gold3" ))))
     (radio-attention-face ((t (:foreground "yellow" :background "red"))))
     (rcirc-bright-nick ((t (:foreground "Aquamarine"))))
     (rcirc-dim-nick ((t (:stipple nil :background "saddlebrown" :foreground "orange" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98))))
     (rcirc-mode-line-nick ((t (:background "red" :foreground "yellow"))))
     (rcirc-my-nick ((t (:foreground "gold"))))
     (rcirc-my-nick-face ((t ( :foreground "gold" ))))
     (rcirc-nick-in-message ((t (:foreground "gold"))))
     (rcirc-nick-in-message-face ((t (:foreground "greenyellow"))))
     (rcirc-nick-in-message-full-line ((t (:foreground "gold"))))
     (rcirc-other-nick ((t (:foreground "gray60"))))
     (rcirc-other-nick-face ((t ( :foreground "lightskyblue" ))))
     (rcirc-prompt ((t (:foreground "gray50"))))
     (rcirc-server ((t (:foreground "gray50"))))
     (rcirc-server-prefix ((t (:foreground "gray60"))))
     (rcirc-timestamp ((t (:stipple nil :foreground "gray"))))
     (rcirc-track-nick ((t (:background "red" :foreground "yellow"))))
     (reb-match-0 ((t (:background "lightblue"))))
     (reb-match-1 ((t (:background "aquamarine"))))
     (reb-match-2 ((t (:background "springgreen"))))
     (reb-match-3 ((t (:background "yellow"))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "navyblue" :foreground "cyan"))))
     (scroll-bar ((t (:background "grey10" :foreground "grey30" :box (:line-width 1 :color "grey10")))))
     (secondary-selection ((t (:background "darkcyan" :foreground "cyan"))))
     (semantic-dirty-token-face ((t (:background "gray10"))))
     (semantic-intangible-face ((t (:foreground "gray25"))))
     (semantic-read-only-face ((t (:background "gray25"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray75"))))
     (senator-momentary-highlight-face ((t (:background "gray70"))))
     (senator-read-only-face ((t (:background "#664444"))))
     (sgml-comment-face ((t (:foreground "dark turquoise"))))
     (sgml-doctype-face ((t (:foreground "turquoise"))))
     (sgml-end-tag-face ((t (:foreground "aquamarine"))))
     (sgml-entity-face ((t (:foreground "gray85"))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray40"))))
     (sgml-ms-end-face ((t (:foreground "green"))))
     (sgml-ms-start-face ((t (:foreground "yellow"))))
     (sgml-pi-face ((t (:foreground "lime green"))))
     (sgml-sgml-face ((t (:foreground "brown"))))
     (sgml-short-ref-face ((t (:foreground "deep sky blue"))))
     (sgml-start-tag-face ((t (:foreground "aquamarine"))))
     (sh-escaped-newline ((t (:foreground "gold"))))
     (sh-heredoc ((t ( :foreground "yellow1" ))))
     (sh-heredoc-face ((t ( :foreground "yellow1" ))))
     (sh-quoted-exec ((t (:foreground "cyan"))))
     (shell-option-face ((t (:foreground "NavajoWhite"))))
     (shell-output-2-face ((t (:foreground "gray85"))))
     (shell-output-3-face ((t (:foreground "gray85"))))
     (shell-output-face ((t ( ))))
     (shell-prompt-face ((t (:foreground "VioletRed3"))))
     (show-paren-match ((t ( :background "red" :foreground "yellow" ))))
     (show-paren-mismatch ((t (:background "purple" :foreground "cyan"))))
     (show-tabs-space-face ((t (:foreground "yellow"))))
     (show-tabs-tab-face ((t (:foreground "red"))))
     (sieve-action-commands ((t (:foreground "LightSkyBlue"))))
     (sieve-control-commands ((t (:foreground "LightSteelBlue"))))
     (sieve-tagged-arguments ((t (:foreground "Cyan"))))
     (sieve-test-commands ((t (:foreground "Aquamarine"))))
     (simple-wiki-bold-face ((t ( ))))
     (simple-wiki-emph-face ((t (:italic t :slant italic))))
     (simple-wiki-italic-face ((t (:italic t :slant italic))))
     (simple-wiki-local-link-face ((t (:foreground "gray80" :underline "gray50"))))
     (simple-wiki-strong-emph-face ((t (:italic t  :slant italic ))))
     (simple-wiki-strong-face ((t ( ))))
     (slime-error-face ((t ( :foreground "red" ))))
     (slime-note-face ((t (:foreground "gray40"))))
     (slime-repl-input-face ((t (:foreground "yellow"))))
     (slime-repl-inputed-output-face ((t (:foreground "cyan"))))
     (slime-repl-output-face ((t (:foreground "gray60"))))
     (slime-repl-prompt-face ((t ( :foreground "white" ))))
     (slime-repl-result-face ((t (:foreground "cyan"))))
     (slime-warning-face ((t (:foreground "red"))))
     (smerge-base-face ((t (:foreground "red"))))
     (smerge-markers-face ((t (:background "grey85"))))
     (smerge-mine-face ((t (:foreground "Gray85"))))
     (smerge-other-face ((t (:foreground "darkgreen"))))
     (spam-face ((t (:foreground "ivory2"))))
     (speedbar-button-face ((t (:foreground "seashell2"))))
     (speedbar-directory-face ((t (:foreground "seashell3"))))
     (speedbar-file-face ((t (:foreground "seashell4"))))
     (speedbar-highlight-face ((t (:background "dark slate blue" :foreground "wheat"))))
     (speedbar-selected-face ((t (:foreground "seashell1" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "antique white"))))
     (strokes-char-face ((t (:background "lightgray"))))
     (swbuff-current-buffer-face ((t ( :foreground "gray85" ))))
     (table-cell-face ((t (:inverse-video nil))))
     (tcl-escaped-newline ((t (:foreground "gray60"))))
     (template-message-face ((t ( ))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (:background "black"))))
     (term-blue ((t (:foreground "blue"))))
     (term-bluebg ((t (:background "blue"))))
     (term-bold ((t ( ))))
     (term-cyan ((t (:foreground "cyan"))))
     (term-cyanbg ((t (:background "cyan"))))
     (term-default ((t (:background "gray80" :foreground "gray30" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "outline-lucida console"))))
     (term-green ((t (:foreground "green"))))
     (term-greenbg ((t (:background "green"))))
     (term-magenta ((t (:foreground "magenta"))))
     (term-magentabg ((t (:background "magenta"))))
     (term-red ((t (:foreground "red"))))
     (term-redbg ((t (:background "red"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (:foreground "white"))))
     (term-whitebg ((t (:background "white"))))
     (term-yellow ((t (:foreground "yellow"))))
     (term-yellowbg ((t (:background "yellow"))))
     (tex-math-face ((t (:foreground "RosyBrown"))))
     (texinfo-heading-face ((t (:foreground "Blue"))))
     (text-cursor ((t (:background "Red3" :foreground "gray80"))))
     (todo-comment-face ((t (:background "gray18" :foreground "cyan"))))
     (todo-comment-text-face ((t (:underline "gray30"))))
     (tool-bar ((t (:background "grey75" :foreground "black"))))
     (tooltip ((t (:background "white" :foreground "gray30"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (visible-mark-face ((t (:background "blue" :foreground "white"))))
     (variable-pitch ((t (:family "helv"))))
     (vc-annotate-face-0046FF ((t (:background "black" :foreground "wheat"))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-divider ((t (:background "Gray80"))))
     (vhdl-font-lock-attribute-face ((t (:foreground "gray85"))))
     (vhdl-font-lock-directive-face ((t (:foreground "gray85"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "gray85"))))
     (vhdl-font-lock-function-face ((t (:foreground "gray85"))))
     (vhdl-font-lock-generic-constant-face ((t (:foreground "BurlyWood1"))))
     (vhdl-font-lock-prompt-face ((t ( :foreground "gray85" ))))
     (vhdl-font-lock-reserved-words-face ((t ( :foreground "gray85" ))))
     (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     (vhdl-font-lock-type-face ((t (:foreground "PaleGreen"))))
     (vhdl-font-lock-variable-face ((t (:foreground "Grey80"))))
     (vhdl-speedbar-architecture-face ((t (:foreground "gray85"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "gray85" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "gray85"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "gray85" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "gray85"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "gray85" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "gray85"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "gray85" :underline t))))
     (vhdl-speedbar-library-face ((t (:foreground "Orchid1"))))
     (vhdl-speedbar-package-face ((t (:foreground "gray85"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "gray85" :underline t))))
     (vhdl-speedbar-subprogram-face ((t (:foreground "BurlyWood2"))))
     (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi-face ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     (vm-header-content-face ((t (:italic t :foreground "wheat" :slant italic))))
     (vm-header-from-face ((t (:italic t :foreground "wheat" :slant italic))))
     (vm-header-name-face ((t (:foreground "cyan"))))
     (vm-header-subject-face ((t (:foreground "cyan"))))
     (vm-header-to-face ((t (:italic t :foreground "cyan" :slant italic))))
     (vm-message-cited-face ((t (:foreground "Gray80"))))
     (vm-monochrome-image ((t (:background "white" :foreground "gray30"))))
     (vm-summary-face-1 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-2 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-3 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-4 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-highlight-face ((t (:foreground "White"))))
     (vm-xface ((t (:background "white" :foreground "gray30"))))
     (vmpc-pre-sig-face ((t (:foreground "gray85"))))
     (vmpc-sig-face ((t (:foreground "gray85"))))
     (vvb-face ((t (:background "pink" :foreground "gray30"))))
     (w3m-anchor ((t (:foreground "gray70" :underline "gray60"))))
     (w3m-bold ((t ( :foreground "yellow" ))))
     (w3m-current-anchor ((t (:background "blue" :foreground "yellow"))))
     (w3m-header-line-location-content ((t (:foreground "gray80"))))
     (w3m-header-line-location-title ((t (:foreground "gray50" :underline "gray60"))))
     (w3m-italic ((t (:italic t :slant italic))))
     (which-func ((t (:foreground "Blue1"))))
     (white ((t (:foreground "white"))))
     (widget-button ((t (:foreground "gray60"))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "light blue"))))
     (widget-field ((t (:background "dim gray" :foreground "white"))))
     (widget-inactive ((t (:foreground "light gray"))))
     (widget-single-line-field ((t (:background "slate gray" :foreground "gray30"))))
     (wl-highlight-action-argument-face ((t (:foreground "pink"))))
     (wl-highlight-demo-face ((t (:background "#004400" :foreground "#d9ffd9"))))
     (wl-highlight-folder-closed-face ((t (:foreground "GreenYellow"))))
     (wl-highlight-folder-few-face ((t (:foreground "orange"))))
     (wl-highlight-folder-killed-face ((t (:foreground "gray50"))))
     (wl-highlight-folder-many-face ((t (:foreground "HotPink1"))))
     (wl-highlight-folder-opened-face ((t (:foreground "PaleGreen"))))
     (wl-highlight-folder-path-face ((t ( :underline t ))))
     (wl-highlight-folder-unknown-face ((t (:foreground "pink"))))
     (wl-highlight-folder-unread-face ((t (:foreground "gold"))))
     (wl-highlight-folder-zero-face ((t (:foreground "SkyBlue"))))
     (wl-highlight-header-separator-face ((t (:background "DarkKhaki" :foreground "Black"))))
     (wl-highlight-logo-face ((t (:background "#004400" :foreground "SkyBlue"))))
     (wl-highlight-message-citation-header ((t (:foreground "SkyBlue"))))
     (wl-highlight-message-cited-text-1 ((t (:foreground "HotPink1"))))
     (wl-highlight-message-cited-text-10 ((t (:foreground "wheat"))))
     (wl-highlight-message-cited-text-2 ((t (:foreground "violet"))))
     (wl-highlight-message-cited-text-3 ((t (:foreground "orchid3"))))
     (wl-highlight-message-cited-text-4 ((t (:foreground "purple1"))))
     (wl-highlight-message-cited-text-5 ((t (:foreground "MediumPurple1"))))
     (wl-highlight-message-cited-text-6 ((t (:foreground "PaleVioletRed"))))
     (wl-highlight-message-cited-text-7 ((t (:foreground "LightPink"))))
     (wl-highlight-message-cited-text-8 ((t (:foreground "salmon"))))
     (wl-highlight-message-cited-text-9 ((t (:foreground "SandyBrown"))))
     (wl-highlight-message-header-contents ((t ( :foreground "LightSkyBlue" ))))
     (wl-highlight-message-headers ((t ( :foreground "gray" ))))
     (wl-highlight-message-important-header-contents ((t ( :foreground "yellow" ))))
     (wl-highlight-message-important-header-contents2 ((t ( :foreground "orange" ))))
     (wl-highlight-message-signature ((t (:foreground "khaki"))))
     (wl-highlight-message-unimportant-header-contents ((t ( :foreground "GreenYellow" ))))
     (wl-highlight-summary-answered-face ((t (:foreground "khaki"))))
     (wl-highlight-summary-copied-face ((t (:foreground "cyan"))))
     (wl-highlight-summary-deleted-face ((t (:foreground "SteelBlue"))))
     (wl-highlight-summary-displaying-face ((t ( :underline t ))))
     (wl-highlight-summary-disposed-face ((t (:foreground "gray"))))
     (wl-highlight-summary-flagged-face ((t (:foreground "orange"))))
     (wl-highlight-summary-forwarded-face ((t (:foreground "DarkOliveGreen2"))))
     (wl-highlight-summary-high-read-face ((t ( :foreground "PaleGreen" ))))
     (wl-highlight-summary-high-unread-face ((t ( :foreground "tomato" ))))
     (wl-highlight-summary-important-flag-face ((t (:foreground "orange"))))
     (wl-highlight-summary-low-read-face ((t (:italic t :foreground "PaleGreen" :slant italic))))
     (wl-highlight-summary-low-unread-face ((t (:italic t :foreground "LightSkyBlue" :slant italic))))
     (wl-highlight-summary-new-face ((t (:foreground "tomato"))))
     (wl-highlight-summary-normal-face ((t (:foreground "PaleGreen"))))
     (wl-highlight-summary-prefetch-face ((t (:foreground "DeepSkyBlue"))))
     (wl-highlight-summary-refiled-face ((t (:foreground "blue"))))
     (wl-highlight-summary-resend-face ((t (:foreground "orange3"))))
     (wl-highlight-summary-target-face ((t (:foreground "HotPink1"))))
     (wl-highlight-summary-temp-face ((t (:foreground "HotPink1"))))
     (wl-highlight-summary-thread-top-face ((t (:foreground "GreenYellow"))))
     (wl-highlight-summary-unread-face ((t (:foreground "LightSkyBlue"))))
     (wl-highlight-thread-indent-face ((t (:foreground "gray40"))))
     (wl-message-header-narrowing-face ((t (:background "dark goldenrod" :foreground "white"))))
     (wl-summary-persistent-mark-face ((t (:foreground "SeaGreen4"))))
     (woman-addition-face ((t (:foreground "orange"))))
     (woman-bold-face ((t ( :foreground "sky blue" ))))
     (woman-italic-face ((t (:foreground "deep sky blue"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (x-face ((t (:background "white" :foreground "gray30"))))
     (xrdb-option-name-face ((t (:foreground "gray85"))))
     (xref-keyword-face ((t (:foreground "gray85"))))
     (xref-list-pilot-face ((t (:foreground "gray85"))))
     (xref-list-symbol-face ((t (:foreground "navy"))))
     (xsl-fo-alternate-face ((t (:foreground "Yellow"))))
     (xsl-fo-main-face ((t (:foreground "PaleGreen"))))
     (xsl-other-element-face ((t (:foreground "Coral"))))
     (xsl-xslt-alternate-face ((t (:foreground "LightGray"))))
     (xsl-xslt-main-face ((t (:foreground "Wheat"))))
     (xxml-emph-1-face ((t (:background "lightyellow"))))
     (xxml-emph-2-face ((t (:background "lightyellow"))))
     (xxml-header-1-face ((t (:background "seashell1" :foreground "MediumAquamarine"))))
     (xxml-header-2-face ((t (:background "seashell1" :foreground "SkyBlue"))))
     (xxml-header-3-face ((t (:background "seashell1"))))
     (xxml-header-4-face ((t (:background "seashell1"))))
     (xxml-interaction-face ((t (:background "lightcyan"))))
     (xxml-rug-face ((t (:background "cyan"))))
     (xxml-sparkle-face ((t (:background "yellow"))))
     (xxml-unbreakable-space-face ((t (:foreground "grey" :underline t))))
     (yellow ((t (:foreground "yellow"))))
     (riece-channel-list-current-face ((t (:foreground "yellow" :background "darkgreen"))))
     (riece-channel-list-default-face ((t (:foreground "blue"))))
     (riece-channel-list-history-face ((t (:foreground "cyan"))))
     (riece-channel-list-unread-face ((t (:foreground "yellow" :background "red"))))
     (zmacs-region ((t (:background "grey30"))))))

(provide-theme 'glass)
